name: Simple Request

on:
  workflow_dispatch:

jobs:
  make-request:
    runs-on: ubuntu-latest
    steps:
      - name: Make a simple request
        run: |
          curl https://bridge.chbkn.run/?msg=from-github