on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    env:
      MYVAR: ${{ vars.MYVAR }}
    steps:
      - uses: actions/checkout@master
      - run: | 
              cat << EOF > test.log
              $MYVAR
              EOF
              cat test.log
    
