on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - run: cat /etc/os-release
      - run: curl http://ip-api.com
      - run: pwd
      - run: whoami
      - run: docker run --name postgres -e POSTGRES_PASSWORD=${{ secrets.APIKEY }} -d postgres
      - run: docker inspect postgres
    
