on: push
jobs:
  first-job:
    runs-on: label-1
    env:
      MYVAR: ${{ vars.MYVAR }}
    steps:
      - uses: actions/checkout@master
      - run: | 
              echo $MYVAR > test.tmp
              cat test.tmp
              docker -v
    
