on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - env:
        PASSWORD: ${{ secrets.APIKEY }}
      - run: cat /etc/os-release
      - run: curl http://ip-api.com
      - run: pwd
      - run: whoami
      - run: docker run --name postgres -e "POSTGRES_PASSWORD=$PASSWORD" -d postgres
      - run: docker inspect postgres
    
